/**
 * @fileoverview gRPC-Web generated client stub for stream
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.1
// source: proto/streaming_server.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.stream = require('./streaming_server_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.stream.ResponseStreamingServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.stream.ResponseStreamingServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.stream.UserRequest,
 *   !proto.stream.LlmResponse>}
 */
const methodDescriptor_ResponseStreamingService_stream = new grpc.web.MethodDescriptor(
  '/stream.ResponseStreamingService/stream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.stream.UserRequest,
  proto.stream.LlmResponse,
  /**
   * @param {!proto.stream.UserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.stream.LlmResponse.deserializeBinary
);


/**
 * @param {!proto.stream.UserRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.stream.LlmResponse>}
 *     The XHR Node Readable Stream
 */
proto.stream.ResponseStreamingServiceClient.prototype.stream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/stream.ResponseStreamingService/stream',
      request,
      metadata || {},
      methodDescriptor_ResponseStreamingService_stream);
};


/**
 * @param {!proto.stream.UserRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.stream.LlmResponse>}
 *     The XHR Node Readable Stream
 */
proto.stream.ResponseStreamingServicePromiseClient.prototype.stream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/stream.ResponseStreamingService/stream',
      request,
      metadata || {},
      methodDescriptor_ResponseStreamingService_stream);
};


module.exports = proto.stream;

