# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/streaming_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/streaming_server.proto\x12\x06stream\"\x1d\n\x0bUserRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\"\n\x0bLlmResponse\x12\x13\n\x0bllm_content\x18\x01 \x01(\t2P\n\x18ResponseStreamingService\x12\x34\n\x06stream\x12\x13.stream.UserRequest\x1a\x13.stream.LlmResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.streaming_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERREQUEST']._serialized_start=40
  _globals['_USERREQUEST']._serialized_end=69
  _globals['_LLMRESPONSE']._serialized_start=71
  _globals['_LLMRESPONSE']._serialized_end=105
  _globals['_RESPONSESTREAMINGSERVICE']._serialized_start=107
  _globals['_RESPONSESTREAMINGSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
