"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class UserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    prompt: builtins.str
    def __init__(
        self,
        *,
        prompt: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["prompt", b"prompt"]) -> None: ...

global___UserRequest = UserRequest

@typing_extensions.final
class LlmResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LLM_CONTENT_FIELD_NUMBER: builtins.int
    llm_content: builtins.str
    def __init__(
        self,
        *,
        llm_content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["llm_content", b"llm_content"]) -> None: ...

global___LlmResponse = LlmResponse
