version: '3'

services:
  fastapi:
    container_name: rest-api
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: base
    restart: always
    tty: true
    volumes:
      - ./backend/fast_api:/app
      - ~/.zshrc:/root/.zshrc
    ports:
      - "5000:5000"
    command: ["gunicorn", "main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:5000", "--timeout", "300", "--access-logfile", "-", "--error-logfile", "-", "--log-level", "debug"]
    expose:
      - "5000"

  grpc-api:
    container_name: grpc-api
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: base
    restart: always
    tty: true
    volumes:
      - ./backend/grpc_api/src:/app
      - ~/.zshrc:/root/.zshrc
    ports:
      - "50051:50051"
    command: ["python", "main.py"]
    expose:
      - "50051"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      target: base
    restart: always
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["yarn", "start"]
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_GRPC_API_URL=http://localhost:50051

  # リバースプロキシ
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: envoy-grpc-proxy
    ports:
      - 9000:9000
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - internal

networks:
  internal:
    driver: bridge
