version: '3'

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: base
    restart: always
    tty: true
    volumes:
      - ./backend/fast_api:/app
      - ~/.zshrc:/root/.zshrc
    ports:
      - "5000:5000"
    networks:
      - internal
    environment:
      - SYSTEM_ENV=development
    command: ["gunicorn", "main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:5000", "--timeout", "300", "--access-logfile", "-", "--error-logfile", "-", "--log-level", "debug"]
    expose:
      - "5000"

  grpc-api:
    container_name: grpc-api
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      target: base
    restart: always
    tty: true
    volumes:
      - ./backend/grpc_api/src:/app
      - ~/.zshrc:/root/.zshrc
    ports:
      - "50051:50051"
    environment:
      - SYSTEM_ENV=development
    command: ["python", "main.py"]
    expose:
      - "50051"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      target: base
    restart: always
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["yarn", "start"]
    networks:
      - internal
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=http://localhost/api/
      - REACT_APP_GRPC_API_URL=http://localhost/grpc/
      - SYSTEM_ENV=development

  # リバースプロキシ(grpc-web)
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - 9000:9000
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - internal

  # リバースプロキシ(nginx)
  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf
    networks:
      - internal
    depends_on:
      - frontend
      - fastapi
      - grpc-api

networks:
  internal:
    driver: bridge
