apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      dnsConfig:
        nameservers:
          - 10.96.0.10
        options:
          - name: ndots
            value: "5"
      dnsPolicy: None
      containers:
      - name: frontend
        image: <your/frontend/image/uri>
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_REST_API_URL
            value: "<your/public/ip>/api/"
          - name: REACT_APP_GRPC_API_URL
            value: "<your/public/ip>/grpc/"
      - name: nginx
        image: <your/nginx/image/uri>
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: rest
        image: <your/rest/image/uri>
        ports:
        - containerPort: 5000
        env:
          - name: OPENAI_API_BASE
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_API_BASE
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_API_KEY
          - name: OPENAI_API_VERSION
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_API_VERSION
          - name: OPENAI_CHAT_ENGINE
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_CHAT_ENGINE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  labels:
    app: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: grpc
        image: <your/grpc/image/uri>
        ports:
        - containerPort: 50051
        env:
          - name: OPENAI_API_BASE
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_API_BASE
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_API_KEY
          - name: OPENAI_API_VERSION
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_API_VERSION
          - name: OPENAI_CHAT_ENGINE
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: OPENAI_CHAT_ENGINE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-web-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-web-envoy
  template:
    metadata:
      labels:
        app: grpc-web-envoy
    spec:
      containers:
      - name: grpc-web-envoy
        image: <your/envoy/image/uri>
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
