FROM node:18 as base
EXPOSE 3000

ENV TZ "Asia/Tokyo"
ENV NODE_ENV "production"
ENV LANG 'ja_JP.UTF-8'

WORKDIR /app
COPY ./frontend ./

CMD ["yarn", "start"]

FROM base as prod

ENV SYSTEM_ENV=production
RUN yarn install --production=true

RUN yarn build
