// @generated by protoc-gen-es v1.5.0 with parameter "target=js+dts"
// @generated from file streaming_server.proto (package stream, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message stream.UserRequest
 */
export declare class UserRequest extends Message<UserRequest> {
  /**
   * @generated from field: string prompt = 1;
   */
  prompt: string;

  constructor(data?: PartialMessage<UserRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "stream.UserRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserRequest;

  static equals(a: UserRequest | PlainMessage<UserRequest> | undefined, b: UserRequest | PlainMessage<UserRequest> | undefined): boolean;
}

/**
 * @generated from message stream.LlmResponse
 */
export declare class LlmResponse extends Message<LlmResponse> {
  /**
   * @generated from field: string llm_content = 1;
   */
  llmContent: string;

  constructor(data?: PartialMessage<LlmResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "stream.LlmResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LlmResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LlmResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LlmResponse;

  static equals(a: LlmResponse | PlainMessage<LlmResponse> | undefined, b: LlmResponse | PlainMessage<LlmResponse> | undefined): boolean;
}

