// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=js+dts"
// @generated from file streaming_server.proto (package stream, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LlmResponse, UserRequest } from "./streaming_server_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service stream.ResponseStreamingService
 */
export declare const ResponseStreamingService: {
  readonly typeName: "stream.ResponseStreamingService",
  readonly methods: {
    /**
     * @generated from rpc stream.ResponseStreamingService.stream
     */
    readonly stream: {
      readonly name: "stream",
      readonly I: typeof UserRequest,
      readonly O: typeof LlmResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
  }
};

