// @generated by protoc-gen-es v1.5.0 with parameter "target=ts"
// @generated from file streaming_server.proto (package stream, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message stream.UserRequest
 */
export class UserRequest extends Message<UserRequest> {
  /**
   * @generated from field: string prompt = 1;
   */
  prompt = "";

  constructor(data?: PartialMessage<UserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stream.UserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserRequest {
    return new UserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserRequest {
    return new UserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserRequest {
    return new UserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UserRequest | PlainMessage<UserRequest> | undefined, b: UserRequest | PlainMessage<UserRequest> | undefined): boolean {
    return proto3.util.equals(UserRequest, a, b);
  }
}

/**
 * @generated from message stream.LlmResponse
 */
export class LlmResponse extends Message<LlmResponse> {
  /**
   * @generated from field: string llm_content = 1;
   */
  llmContent = "";

  constructor(data?: PartialMessage<LlmResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "stream.LlmResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "llm_content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LlmResponse {
    return new LlmResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LlmResponse {
    return new LlmResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LlmResponse {
    return new LlmResponse().fromJsonString(jsonString, options);
  }

  static equals(a: LlmResponse | PlainMessage<LlmResponse> | undefined, b: LlmResponse | PlainMessage<LlmResponse> | undefined): boolean {
    return proto3.util.equals(LlmResponse, a, b);
  }
}

